### ISSUE TITLE
Cancel route change?

### ISSUE THREAD

**Issue by Firfi** [meteorhacks/flow-router#129]
First, I'm rather happy with this package. API is lot cleaner that Iron Router have currently. Still, some not very convenient things there (maybe I use it wrong).

I have such functionality in my application: there's some set of 'restricted' pages that are accessible for parents, and non-restricted that are accessible for parents and children. When child want to go to restricted page, he/she gets login popup instead, where parent should put his/her credentials. I have several ways to get into one 'restricted' page so want logic to be consistent an in one place, and also I don't want to spend user time on template loading, so I went with doing it through routes middlewares. Currently what I can do is call next(FlowRouter.current().oldRoute.path) and it will return me to previous route almost immediately.

That's rather clumsy call though and it still makes URL blink. 

Have any advices?

Thanks!

**Comment by arunoda** [comment]
Yes. I agree this is currently an issue. Our approach for this to move this
functionality into the layout layer or something outside Flow Router.

You can do this in the layout layer or something after routing. Possibly,
via some layout helpers.

I will work on a blog post on this and will publish soon.

This is a known issue and because of that I will close this issue. Feel
free to discuss even this is closed.
