### ISSUE TITLE
Does FlowRouter.reload() destroys the templates and re-creates them?

### ISSUE THREAD

**Issue by sf-wind** [meteorhacks/flow-router#203]
I want to add a refresh button. Once clicked, the page reloads. However, I find that if I use FlowRouter.reload(), some reactive variables I attach to the templates are not cleared, so the data remained the same. I see that the page is reloaded on the same data. But I want to retrieve new data and reloads. The data is retrieved from an external source, so it doesn't get pushed to the client automatically.

**Comment by arunoda** [comment]
FlowRouter.reload() simply run the actions and triggers again. Since your params are not changed, they won't trigger anything.

**Comment by joetidee** [comment]
Is there a way to set a route in the Flowrouter config whereby if a link is clicked (and the browser is already on that page) that reload() gets triggerred?

For example, if I have a link:

<a href="/edit?id=1">Edit</a>

and

<a href="/edit">New</a>

these are linking to the same page, so if I click the second link after clicking the first link the data on the page reamins because Flowrouter does not reload the page. I want to use the same url but clear the page of information.
