### ISSUE TITLE
Callback/Event after isReady block renders

### ISSUE THREAD

**Issue by nakhbari** [meteorhacks/flow-router#219]
You can prevent certain parts of the template from rendering by using an ((#if isReady}} ready helper. The isReady needs for the proper subscription to be loaded before executing the encapsulated elements. 

This is awesome! However, when the subscriptions are loaded and the elements are rendered, I don't think there is a way of figuring out when the elements have finished rendering, such that you can perform your element manipulations. 

The only way i see doing this now is by setting up an autorun around the subscription subsReady function and setting and interval until the elements have finished rendering. Could there be a better/integrated way to handle this. Ideally there would be a callback/event, for example onRenderedSubscription. We can do all our element manipulation there and the world becomes a better place :smile:

**Comment by arunoda** [comment]
Okay. Let me answer this.
Current flow router or flow router can't detect it exactly. But there is a
way to do it. Your approach is correct. But you don't need to do a set
timeout after the subscriptionsReady. Simply use Tracker.afterFlush.
Having said that it's an hack. I think this should be a feature of blaze.
In new rendering systems like React they do rendering asynchronously. So,
it's hard to tell when it's completes the rendering. Also they don't expose
a hook when after rendering because users can misuse that feature.
This is my thinking on this.

**Comment by arunoda** [comment]
I am closing this issue now. But feel free to discuss.
