### ISSUE TITLE
Fast-Render + React

### ISSUE THREAD

**Issue by ccorcos** [meteorhacks/flow-router#29]
Hey there, I've been playing around with React lately and I've been using flow-router instead of iron-router because its way less opinionated (about blaze, particularly). 

Anyways, I'm curious how I could get server-side rendering working. React has this method `React.renderToString` that should make it easy for SSR. This is clearly incomplete, but here's the idea:

https://github.com/ccorcos/meteor-react/blob/master/examples/SSR/main.jsx

I was looking around the fast-render code, and it looks like it relies on (1) subscriptions through flow-router, and (2) Meteor.subscribe. I'd like to use a React mixin to do subscriptions from within the React classes and I'd also like to use subs-manager.

Any suggestions on where/how to get started with this?

Thanks

**Comment by arunoda** [comment]
This is very interesting question and I've no direct answer for this right now.
There is a way we can do this within the flow-router layer.

For that we need to run .action method on the server side. Then we need to create a custom context for Mongo Collections with the data for from subscriptions.

Then we need to rely on fast-render on locally. Otherwise, after the initial load there'll be no data on the client. So, that'll re-render UI with no data.

---

So, here only advantage is SEO support. Otherwise this is just the same as using pure fast-render. 

In order to built a pure SSR support. We need to define a way to write blocking css and JS separately in the head. Then the HTML.(with SSR). After that, load other JS stuff.

This involves a lot of core changes and it's worthy. I can work on these, but I've a lot of stuff on the plate right now :D

**Comment by ccorcos** [comment]
whoa. I was just thinking for SEO. This sounds very involved though. I guess I will just sit eagerly waiting ;)

**Comment by arunoda** [comment]
If that's SEO. I think we'll be fine without SSR pretty soon.
Google can see pages:
https://meteorhacks.com/meteor-seo-google-fetch-and-render.html

**Comment by ccorcos** [comment]
Hmm. So what would I have to do to be able to `cURL` my website?

**Comment by arunoda** [comment]
Hope we can close this.

**Comment by trusktr** [comment]
@arunoda I'm very interested in this too, as might also be people discussing in https://github.com/meteor/meteor/issues/3728 (you are there!).

What's the difference between what fast-render does and pure SSR?

Also, check out [meteor-routecore](https://github.com/mystor/meteor-routecore), which implements pure SSR of React views in Meteor. Maybe you can get some ideas from there?

**Comment by arunoda** [comment]
Yeah! I know route core from back then. They are using fast-render as well.
We need to wait until GraphQL and Relay to get released. They might changed
how we do things.
It might take things simple.
