### ISSUE TITLE
Support different base urls

### ISSUE THREAD

**Issue by mnmtanish** [meteorhacks/flow-router#6]
Set base url with `page.base(path)` using `__meteor_runtime_config__.ROOT_URL_PATH_PREFIX`

**Comment by ogirardot** [comment]
It *really* doesn't seem to work right now. I'm trying to deploy an app based on flow router and I get a "There is not route defined for /my-app " because I didn't deploy it on a virtual host but I did properly set the ROOT_URL and everything else server-side is working.
c.f. : https://github.com/RocketChat/Rocket.Chat/issues/335
